### PR TITLE
Update initZones.sqf

### PR DESCRIPTION
**Pull request by AlexTriada**
Only initZones.sqf without skill changes and fn_local.sqf

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
Hi Alex,
looks interesting what you've done there.
Could you please add some comments within the code where they would be helpful so others can easier understand what happens where?
Also, whilst you were working on that I added 2 new types of markers. Could you please work them into the system?
image

Also, once you have done it, please verify that you have tested it properly.

@Spoffy Once he has implemented it, please check if good to go or if these would leat to problems.

**Comment by AlexTriada** [comment]
Hi Bob,
i dont see in master branch your new types, pls get me the link to this new staff,
simply replace the array of markers to the `islands = ["island"] call _fnc_rw_mrkArray;`

**Comment by AlexTriada** [comment]
looks like no problem, i cheked

**Comment by AlexTriada** [comment]
> Hi Alex,
> looks interesting what you've done there.
> Could you please add some comments within the code where they would be helpful so others can easier understand what happens where?
> Also, whilst you were working on that I added 2 new types of markers. Could you please work them into the system?
> image
> 
> Also, once you have done it, please verify that you have tested it properly.
> 
> @Spoffy Once he has implemented it, please check if good to go or if these would leat to problems.

please write that you do not understand, I will write explanations

**Comment by Bob-Murphy** [comment]
We only work in unstable and update it once we have completed a milestone, tested it and will publish a new update on steam.
For example you can find what i did here dc4d534f25ba1246a3b0c7801c90c4f0a1218005 and d9e35a16fc3006d66dfac1be6178166e22b732bb

Regarding the comments, I don't really understand anything at all but that's not it. Just a rough description of what does what.
For example at the top is still commented out:
```
//deletion of a marker in the array will require deletion of the corresponding marker in the editor
//only touch the commented arrays
```
Maybe just write there that your code automatically ready out all the markers, puts them in arrays or whatever magic your code exactly is doing

**Comment by AlexTriada** [comment]
Ok, i understand, i'll try to comment some most complex places

**Pull request closed without merging**
