### PR TITLE
Adds check for if player is admin to AI Load Info

### PR DESCRIPTION
**Pull request by SonorousMeerkat**
Again, needs testing on an actual host due to my inability to host a game.

### CODE REVIEW

**Comment by Toakan** [comment]
Fix it.

**Comment by Toakan** [comment]
LGTM - Tested on a live server and Members can now request missions.

Further, you cannot grab missions that Petros has already assigned.

**Comment by SonorousMeerkat** [comment]
ignore tads comment

Current check is buggered. Need a working admin checker

**Comment by SonorousMeerkat** [comment]
Travis didn't like that... and i don't know why...

**Comment by Toakan** [comment]
@SonorousMeerkat 

Validating SQF
ERROR: A possible missing square bracket [ or ] in file A3-Antistasi/initPlayerLocal.sqf [ = 178 ] = 177
ERROR: A possible missing curly brace { or } in file A3-Antistasi/initPlayerLocal.sqf { = 194 } = 193

**Comment by SonorousMeerkat** [comment]
now Travis likes it. Needs testing.

**Pull request merged**
